name: waterloupe-service
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - click=8.0.4
  - colorama=0.4.4
  - dataclasses=0.8
  - flask=2.0.3
  - greenlet=1.1.1
  - importlib-metadata=4.11.3
  - itsdangerous=2.0.1
  - jinja2=3.0.3
  - libpq=12.9
  - markupsafe=2.1.1
  - mergedeep
  - openssl=1.1.1o
  - pip=21.2.4
  - psycopg2=2.8.6
  - python=3.7.13
  - setuptools=61.2.0
  - sqlalchemy=1.4.32
  - sqlite=3.38.3
  - typing_extensions=4.1.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.0.3
  - wheel=0.37.1
  - wincertstore=0.2
  - zipp=3.8.0
  - zlib=1.2.12

